# Generated by Django 4.2.13 on 2026-04-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_add_gmail_id_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_virustotal_api_key', models.TextField(blank=True, db_column='virustotal_api_key', default='')),
                ('_abuseipdb_api_key', models.TextField(blank=True, db_column='abuseipdb_api_key', default='')),
                ('gmail_credentials_uploaded', models.BooleanField(default=False)),
                ('gmail_connection_status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTED', 'Connected'), ('EXPIRED', 'Expired')], default='DISCONNECTED', max_length=20)),
                ('gmail_connected_email', models.EmailField(blank=True, max_length=254)),
                ('clean_threshold', models.IntegerField(default=25)),
                ('malicious_threshold', models.IntegerField(default=70)),
                ('fetch_interval_seconds', models.IntegerField(default=10)),
                ('ti_sync_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
